server:
  port: 9003
debug: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka

spring:
  main:
    web-application-type: reactive
  application:
    name: apigateway-service

